#!/bin/bash
# Pull the latest ComfyUI and sync its Python dependencies.
#
# Installed as a separate file rather than being generated by the entrypoint:
# the container runs as an unprivileged user and cannot write to
# /usr/local/bin, and a shipped script is reviewable and shellcheckable.
#
# Runs both at container start and from the update loop. Safe to run repeatedly
# and safe to fail: a failed update leaves the installed version untouched.
set -uo pipefail

COMFYUI_PATH="${COMFYUI_PATH:-/opt/ComfyUI}"

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*"; }

cd "${COMFYUI_PATH}" || { log "FATAL: ${COMFYUI_PATH} is missing"; exit 1; }

if ! git fetch --quiet origin; then
    log "ERROR: git fetch failed (network or ref problem)"
    exit 1
fi

# A detached HEAD (e.g. a tag-pinned build) has no upstream branch to compare
# against, so resolve the branch explicitly rather than assuming.
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ "${BRANCH}" = "HEAD" ]; then
    log "Skipping update: detached HEAD (image pinned to a specific ref)"
    exit 0
fi

LOCAL="$(git rev-parse HEAD)"
REMOTE="$(git rev-parse "origin/${BRANCH}" 2>/dev/null || true)"

if [ -z "${REMOTE}" ]; then
    log "ERROR: cannot resolve origin/${BRANCH}"
    exit 1
fi

if [ "${LOCAL}" = "${REMOTE}" ]; then
    log "ComfyUI already up to date at $(git rev-parse --short HEAD)"
    exit 0
fi

log "Update available: $(git rev-parse --short "${LOCAL}") -> $(git rev-parse --short "${REMOTE}")"

# --ff-only is essential: this is the live application tree, and a merge or
# rebase here would leave a half-updated ComfyUI on disk. If the tree has local
# edits the merge refuses, and the running version is left alone.
if ! git merge --ff-only "origin/${BRANCH}"; then
    log "ERROR: cannot fast-forward (local modifications?). Not updating."
    exit 1
fi

log "Fast-forwarded to $(git rev-parse --short HEAD)"

# A ComfyUI bump can change dependencies, so sync them into the venv. Not
# --upgrade: requirements.txt is the source of truth and forcing upgrades would
# pull versions ComfyUI has not been tested against.
if ! pip install --quiet -r requirements.txt; then
    log "ERROR: dependency sync failed; code updated but deps may not match"
    exit 1
fi

log "Dependencies synced"
exit 0